### ISSUE TITLE
Only getting 2 assertions for this 3 assertion test

### ISSUE THREAD

**Issue by sirrobin11** [plangrid/specford#1]
All of the operations it does end up in the right place, but the "text exists" part does not produce an assertion (it should fail).

visit http://www.plangrid.com/en:
    query body:
    click selector 'div.menu-toggle'
        click selector 'a[class="cta-button cta-button-white headerLoginLink"]'
        after selector 'div.popup-container' exists
        fill 'input[type="text"]' 'tyler@plangrid.com'
        fill 'input[type="password"]' 'password'
        click selector 'button[type="submit"]'
        after text 'Signing in' doesNotExist
        text 'corn' exists
        capture jpeg 'login_screenshot'

**Comment by robrobbins** [comment]
Fixed via latest upstream master merge
